# frozen_string_literal: true

class ChangeDefaultsAndNulls < ActiveRecord::Migration[7.1]
  def change
    change_column_default(:tickets, :handler_id, from: 0, to: nil)
    change_column_null(:tickets, :handler_id, true)
    change_column_default(:bulk_update_requests, :title, from: nil, to: "")
    change_column_null(:bulk_update_requests, :title, false)
    change_column_null(:comment_votes, :user_ip_addr, false)
    change_column_null(:comments, :updater_id, false)
    change_column_null(:comments, :updater_ip_addr, false)
    change_column_null(:destroyed_posts, :uploader_id, false)
    change_column_null(:destroyed_posts, :uploader_ip_addr, false)
    change_column_default(:exception_logs, :extra_params, from: nil, to: "{}")
    change_column_null(:exception_logs, :extra_params, false)
    change_column_null(:forum_posts, :creator_ip_addr, false)
    change_column_null(:forum_topic_visits, :user_id, false)
    change_column_null(:forum_topic_visits, :forum_topic_id, false)
    change_column_null(:pool_versions, :updater_id, false)
    change_column_null(:pool_versions, :updater_ip_addr, false)
    change_column_default(:post_versions, :description, from: nil, to: "")
    change_column_null(:pool_versions, :description, false)
    change_column_default(:pool_versions, :name, from: nil, to: "")
    change_column_null(:pool_versions, :name, false)
    change_column_default(:post_disapprovals, :reason, from: "legacy", to: nil)
    change_column_null(:post_disapprovals, :reason, false)
    change_column_default(:post_disapprovals, :message, from: nil, to: "")
    change_column_null(:post_disapprovals, :message, false, "")
    change_column_null(:post_flags, :reason, false)
    change_column_null(:post_flags, :updated_at, false)
    change_column_default(:post_replacements, :source, from: nil, to: "")
    change_column_null(:post_replacements, :source, false)
    change_column_null(:post_sets, :creator_ip_addr, false)
    change_column_default(:post_versions, :locked_tags, from: nil, to: "")
    change_column_null(:post_versions, :locked_tags, false, "")
    change_column_null(:post_versions, :updater_id, false)
    change_column_null(:post_versions, :rating, false)
    change_column_default(:post_versions, :source, from: nil, to: "")
    change_column_null(:post_versions, :source, false)
    change_column_default(:post_versions, :description, from: nil, to: "")
    change_column_null(:post_versions, :description, false)
    change_column_null(:post_votes, :user_ip_addr, false)
    change_column_default(:posts, :locked_tags, from: nil, to: "")
    change_column_null(:posts, :locked_tags, false, "")
    change_column_default(:staff_audit_logs, :values, from: nil, to: "{}")
    change_column_null(:staff_audit_logs, :values, false)
    change_column_null(:staff_notes, :body, false)
    change_column_null(:takedowns, :status, false)
    change_column_default(:takedowns, :source, from: nil, to: "")
    change_column_null(:takedowns, :source, false, "")
    change_column_null(:takedowns, :email, false, "")
    change_column_default(:takedowns, :reason, from: nil, to: "")
    change_column_null(:takedowns, :reason, false, "")
    change_column_default(:takedowns, :instructions, from: nil, to: "")
    change_column_null(:takedowns, :instructions, false, "")
    change_column_null(:takedowns, :post_ids, false)
    change_column_null(:takedowns, :del_post_ids, false)
    change_column_null(:user_feedbacks, :creator_ip_addr, false)
    change_column_null(:user_feedbacks, :updater_id, false)
    change_column_null(:user_name_change_requests, :original_name, false)
    change_column_null(:user_name_change_requests, :desired_name, false)
    change_column_default(:user_name_change_requests, :change_reason, from: nil, to: "")
    change_column_null(:user_name_change_requests, :change_reason, false)
    change_column_default(:users, :custom_style, from: nil, to: "")
    change_column_null(:users, :custom_style, false, "")
    change_column_null(:wiki_pages, :updater_id, false)
  end
end
