# frozen_string_literal: true

class AddMissingForeignKeys < ActiveRecord::Migration[7.1]
  def change
    add_foreign_key(:api_keys, :users)
    add_foreign_key(:artist_urls, :artists)
    add_foreign_key(:artist_versions, :artists)
    add_foreign_key(:artist_versions, :users, column: :updater_id)
    add_foreign_key(:artists, :users, column: :creator_id)
    add_foreign_key(:artists, :users, column: :linked_user_id)
    add_foreign_key(:bans, :users)
    add_foreign_key(:bans, :users, column: :banner_id)
    add_foreign_key(:bulk_update_requests, :users, column: :creator_id)
    add_foreign_key(:bulk_update_requests, :forum_topics, on_delete: :nullify)
    add_foreign_key(:bulk_update_requests, :forum_posts, on_delete: :nullify)
    add_foreign_key(:bulk_update_requests, :users, column: :approver_id)
    add_foreign_key(:comment_votes, :comments)
    add_foreign_key(:comment_votes, :users)
    add_foreign_key(:comments, :posts)
    add_foreign_key(:comments, :users, column: :creator_id)
    add_foreign_key(:comments, :users, column: :updater_id)
    add_foreign_key(:comments, :users, column: :warning_user_id)
    add_foreign_key(:destroyed_posts, :users, column: :destroyer_id)
    add_foreign_key(:destroyed_posts, :users, column: :uploader_id)
    add_foreign_key(:dmail_filters, :users)
    add_foreign_key(:dmails, :users, column: :owner_id)
    add_foreign_key(:dmails, :users, column: :from_id)
    add_foreign_key(:dmails, :users, column: :to_id)
    add_foreign_key(:edit_histories, :users)
    add_foreign_key(:email_blacklists, :users, column: :creator_id)
    add_foreign_key(:exception_logs, :users)
    add_foreign_key(:forum_post_votes, :forum_posts)
    add_foreign_key(:forum_post_votes, :users)
    add_foreign_key(:forum_posts, :forum_topics, column: :topic_id)
    add_foreign_key(:forum_posts, :users, column: :creator_id)
    add_foreign_key(:forum_posts, :users, column: :updater_id)
    add_foreign_key(:forum_posts, :users, column: :warning_user_id)
    add_foreign_key(:forum_topic_statuses, :users)
    add_foreign_key(:forum_topic_statuses, :forum_topics)
    add_foreign_key(:forum_topic_visits, :users)
    add_foreign_key(:forum_topic_visits, :forum_topics)
    add_foreign_key(:forum_topics, :users, column: :creator_id)
    add_foreign_key(:forum_topics, :users, column: :updater_id)
    add_foreign_key(:forum_topics, :forum_categories, column: :category_id)
    add_foreign_key(:ip_bans, :users, column: :creator_id)
    add_foreign_key(:mod_actions, :users, column: :creator_id)
    add_foreign_key(:news_updates, :users, column: :creator_id)
    add_foreign_key(:news_updates, :users, column: :updater_id)
    add_foreign_key(:note_versions, :notes)
    add_foreign_key(:note_versions, :posts)
    add_foreign_key(:note_versions, :users, column: :updater_id)
    add_foreign_key(:notes, :users, column: :creator_id)
    add_foreign_key(:notes, :posts)
    add_foreign_key(:notifications, :users)
    add_foreign_key(:pool_versions, :pools)
    add_foreign_key(:pool_versions, :users, column: :updater_id)
    add_foreign_key(:pools, :users, column: :creator_id)
    add_foreign_key(:post_approvals, :users)
    add_foreign_key(:post_approvals, :posts)
    add_foreign_key(:post_disapprovals, :users)
    add_foreign_key(:post_disapprovals, :posts)
    # add_foreign_key(:post_events, :posts)
    add_foreign_key(:post_flags, :users, column: :creator_id)
    add_foreign_key(:post_flags, :posts)
    add_foreign_key(:post_replacements, :posts)
    add_foreign_key(:post_replacements, :users, column: :creator_id)
    add_foreign_key(:post_replacements, :users, column: :approver_id)
    add_foreign_key(:post_replacements, :users, column: :uploader_id_on_approve)
    add_foreign_key(:post_set_maintainers, :post_sets)
    add_foreign_key(:post_set_maintainers, :users)
    add_foreign_key(:post_sets, :users, column: :creator_id)
    add_foreign_key(:post_versions, :posts)
    add_foreign_key(:post_versions, :users, column: :updater_id)
    # add_foreign_key(:post_versions, :posts, column: :parent_id, on_delete: :nullify)
    add_foreign_key(:post_votes, :posts)
    add_foreign_key(:post_votes, :users)
    add_foreign_key(:posts, :users, column: :uploader_id)
    add_foreign_key(:posts, :users, column: :approver_id)
    add_foreign_key(:quick_rules, :rules)
    add_foreign_key(:staff_notes, :users, column: :creator_id)
    add_foreign_key(:tag_aliases, :users, column: :creator_id)
    add_foreign_key(:tag_aliases, :users, column: :approver_id)
    add_foreign_key(:tag_aliases, :forum_posts, on_delete: :nullify)
    add_foreign_key(:tag_aliases, :forum_topics, on_delete: :nullify)
    add_foreign_key(:tag_followers, :tags)
    add_foreign_key(:tag_followers, :users)
    add_foreign_key(:tag_implications, :users, column: :creator_id)
    add_foreign_key(:tag_implications, :users, column: :approver_id)
    add_foreign_key(:tag_implications, :forum_posts, on_delete: :nullify)
    add_foreign_key(:tag_implications, :forum_topics, on_delete: :nullify)
    add_foreign_key(:tag_versions, :tags)
    add_foreign_key(:tag_versions, :users, column: :updater_id)
    add_foreign_key(:takedowns, :users, column: :creator_id)
    add_foreign_key(:takedowns, :users, column: :approver_id)
    add_foreign_key(:tickets, :users, column: :creator_id)
    add_foreign_key(:tickets, :users, column: :handler_id)
    add_foreign_key(:uploads, :users, column: :uploader_id)
    add_foreign_key(:uploads, :posts)
    # add_foreign_key(:uploads, :posts, column: :parent_id)
    add_foreign_key(:user_blocks, :users)
    add_foreign_key(:user_feedbacks, :users)
    add_foreign_key(:user_feedbacks, :users, column: :creator_id)
    add_foreign_key(:user_name_change_requests, :users)
    add_foreign_key(:user_name_change_requests, :users, column: :approver_id)
    add_foreign_key(:user_password_reset_nonces, :users)
    add_foreign_key(:user_text_versions, :users)
    add_foreign_key(:users, :posts, column: :avatar_id)
    add_foreign_key(:wiki_page_versions, :wiki_pages)
    add_foreign_key(:wiki_page_versions, :users, column: :updater_id)
    add_foreign_key(:wiki_pages, :users, column: :creator_id)
    add_foreign_key(:wiki_pages, :users, column: :updater_id)
  end
end
